# Generated by Django 4.2.3 on 2023-09-17 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_subscribeduserscategory_category_subscribed_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='subscribed_users',
            new_name='subscribers',
        ),
    ]
